/// for messages
const users = [
  {
    name: "John Doe",
    message: "Pick me at 9:00 AM",
    image: "/images/placeholder-614.webp",
    time: "9:00 AM",
    id: 1,
  },
  {
    name: "Jane Smith",
    message: "Hi Sam, Welcome",
    image: "/images/placeholder-614.webp",
    time: "9:00 AM",
    id: 2,
  },
  {
    name: "Michael Johnson",
    message: "Micheal : Thanks Everyone",
    image: "/images/placeholder-614.webp",
    time: "9:00 AM",
    id: 3,
  },
  {
    name: "Sarah Thompson",
    message: "Sarah : some one can fix this",
    image: "/images/placeholder-614.webp",
    time: "9:00 AM",
    id: 4,
  },
  {
    name: "David Wilson",
    message: "David : some one can fix this",
    image: "/images/placeholder-614.webp",
    time: "9:00 AM",
    id: 5,
  },
  {
    name: "Emily Davis",
    message: "Emily : some one can fix this",
    image: "/images/placeholder-614.webp",
    time: "9:00 AM",
    id: 6,
  },
  {
    name: "Daniel Anderson",
    message: "Daniel : some one can fix this",
    image: "/images/placeholder-614.webp",
    time: "9:00 AM",
    id: 7,
  },

  {
    name: "React Developers",
    message: "New hooks tutorial available",
    image: "/images/placeholder-614.webp",
    time: "10:15 AM",
    id: 8,
  },
  {
    name: "Vue Vixens",
    message: "Join our Vue3 webinar",
    image: "/images/placeholder-614.webp",
    time: "11:00 AM",
    id: 9,
  },
  {
    name: "Angular Architects",
    message: "Monthly meeting rescheduled",
    image: "/images/placeholder-614.webp",
    time: "12:45 PM",
    id: 10,
  },
  {
    name: "Python Programmers",
    message: "Hackathon next weekend",
    image: "/images/placeholder-614.webp",
    time: "1:30 PM",
    id: 11,
  },
  {
    name: "Flutter Friends",
    message: "State management discussion",
    image: "/images/placeholder-614.webp",
    time: "2:15 PM",
    id: 12,
  },
  {
    name: "Node.js Ninjas",
    message: "Express vs Koa - which is better?",
    image: "/images/placeholder-614.webp",
    time: "3:00 PM",
    id: 13,
  },
  {
    name: "Blockchain Buffs",
    message: "Smart contract workshop",
    image: "/images/placeholder-614.webp",
    time: "3:45 PM",
    id: 14,
  },
  {
    name: "AI Enthusiasts",
    message: "New ML model released",
    image: "/images/placeholder-614.webp",
    time: "4:30 PM",
    id: 15,
  },
  {
    name: "Cybersecurity Circle",
    message: "Vulnerability analysis session",
    image: "/images/placeholder-614.webp",
    time: "5:15 PM",
    id: 16,
  },
  {
    name: "DevOps Dudes",
    message: "CI/CD pipeline setup guide",
    image: "/images/placeholder-614.webp",
    time: "6:00 PM",
    id: 17,
  },
];

/// ongoing jobs data
const ongoingProjects = [
  {
    projectName: "E-commerce Website Redesign",
    category: "Web Development",
    description:
      "Redesign and optimize an existing e-commerce website for better UX/UI.",
    budget: "$5,000",
    deadline: "Sep 30, 2024",
    clientName: "Alice Tech Solutions",
  },
  {
    projectName: "Mobile App for Delivery",
    category: "Mobile Development",
    description:
      "Develop a cross-platform mobile app for a local delivery service.",
    budget: "$8,500",
    deadline: "Oct 15, 2024",
    clientName: "Urban Courier Inc.",
  },
  {
    projectName: "Marketing Automation Setup",
    category: "Digital Marketing",
    description:
      "Implement a marketing automation platform for targeted campaigns.",
    budget: "$3,200",
    deadline: "Sep 20, 2024",
    clientName: "BrightStar Media",
  },
  {
    projectName: "Custom CRM Development",
    category: "Software Development",
    description:
      "Build a custom CRM solution tailored for a mid-sized business.",
    budget: "$12,000",
    deadline: "Nov 1, 2024",
    clientName: "Prime Business Co.",
  },
  {
    projectName: "Data Analysis Tool",
    category: "Data Science & Analytics",
    description:
      "Develop a tool for analyzing sales data and generating reports.",
    budget: "$4,500",
    deadline: "Sep 25, 2024",
    clientName: "Data Insights Ltd.",
  },
  {
    projectName: "E-commerce Website Redesign",
    category: "Web Development",
    description:
      "Redesign and optimize an existing e-commerce website for better UX/UI.",
    budget: "$5,000",
    deadline: "Sep 30, 2024",
    clientName: "Alice Tech Solutions",
  },
  {
    projectName: "Mobile App for Delivery",
    category: "Mobile Development",
    description:
      "Develop a cross-platform mobile app for a local delivery service.",
    budget: "$8,500",
    deadline: "Oct 15, 2024",
    clientName: "Urban Courier Inc.",
  },
  {
    projectName: "Marketing Automation Setup",
    category: "Digital Marketing",
    description:
      "Implement a marketing automation platform for targeted campaigns.",
    budget: "$3,200",
    deadline: "Sep 20, 2024",
    clientName: "BrightStar Media",
  },
  {
    projectName: "Custom CRM Development",
    category: "Software Development",
    description:
      "Build a custom CRM solution tailored for a mid-sized business.",
    budget: "$12,000",
    deadline: "Nov 1, 2024",
    clientName: "Prime Business Co.",
  },
  {
    projectName: "Data Analysis Tool",
    category: "Data Science & Analytics",
    description:
      "Develop a tool for analyzing sales data and generating reports.",
    budget: "$4,500",
    deadline: "Sep 25, 2024",
    clientName: "Data Insights Ltd.",
  },
];

const languageTags = [
  // Popular spoken languages
  "English",
  "Spanish",
  "French",
  "German",
  "Mandarin Chinese",
  "Hindi",
  "Portuguese",
  "Bengali",
  "Russian",
  "Arabic",
  "Italian",
  "Japanese",
  "Korean",
  "Turkish",
  "Dutch",
  "Polish",
  "Swedish",
  "Greek",
  "Hebrew",
  "Danish",
  "Norwegian",
  "Finnish",
  "Thai",
  "Vietnamese",
  "Malay",
  "Indonesian",
  "Filipino",
  "Persian (Farsi)",
  "Urdu",
  "Tamil",
  "Telugu",
  "Marathi",
  "Punjabi",
  "Gujarati",
  "Czech",
  "Hungarian",
  "Romanian",
  "Slovak",
  "Serbian",
  "Ukrainian",
  "Bulgarian",
  "Croatian",
  "Swahili",
  "Zulu",
  "Afrikaans",
  "Hausa",
  "Yoruba",
  "Nepali",
  "Nepal Bhasa",
  "Gurung",
];

const countries = [
  { name: "Afghanistan", code: "AF" },
  { name: "Åland Islands", code: "AX" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "American Samoa", code: "AS" },
  { name: "AndorrA", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Anguilla", code: "AI" },
  { name: "Antarctica", code: "AQ" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Aruba", code: "AW" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bermuda", code: "BM" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Bouvet Island", code: "BV" },
  { name: "Brazil", code: "BR" },
  { name: "British Indian Ocean Territory", code: "IO" },
  { name: "Brunei Darussalam", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Cape Verde", code: "CV" },
  { name: "Cayman Islands", code: "KY" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Christmas Island", code: "CX" },
  { name: "Cocos (Keeling) Islands", code: "CC" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo", code: "CG" },
  { name: "Congo, The Democratic Republic of the", code: "CD" },
  { name: "Cook Islands", code: "CK" },
  { name: "Costa Rica", code: "CR" },
  { name: "Cote D'Ivoire", code: "CI" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Ethiopia", code: "ET" },
  { name: "Falkland Islands (Malvinas)", code: "FK" },
  { name: "Faroe Islands", code: "FO" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "French Guiana", code: "GF" },
  { name: "French Polynesia", code: "PF" },
  { name: "French Southern Territories", code: "TF" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Gibraltar", code: "GI" },
  { name: "Greece", code: "GR" },
  { name: "Greenland", code: "GL" },
  { name: "Grenada", code: "GD" },
  { name: "Guadeloupe", code: "GP" },
  { name: "Guam", code: "GU" },
  { name: "Guatemala", code: "GT" },
  { name: "Guernsey", code: "GG" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Heard Island and Mcdonald Islands", code: "HM" },
  { name: "Holy See (Vatican City State)", code: "VA" },
  { name: "Honduras", code: "HN" },
  { name: "Hong Kong", code: "HK" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran, Islamic Republic Of", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Isle of Man", code: "IM" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jersey", code: "JE" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Korea, Democratic People'S Republic of", code: "KP" },
  { name: "Korea, Republic of", code: "KR" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Lao People'S Democratic Republic", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libyan Arab Jamahiriya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Macao", code: "MO" },
  { name: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Martinique", code: "MQ" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mayotte", code: "YT" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia, Federated States of", code: "FM" },
  { name: "Moldova, Republic of", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montserrat", code: "MS" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "Netherlands Antilles", code: "AN" },
  { name: "New Caledonia", code: "NC" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Niue", code: "NU" },
  { name: "Norfolk Island", code: "NF" },
  { name: "Northern Mariana Islands", code: "MP" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestinian Territory, Occupied", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Pitcairn", code: "PN" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Puerto Rico", code: "PR" },
  { name: "Qatar", code: "QA" },
  { name: "Reunion", code: "RE" },
  { name: "Romania", code: "RO" },
  { name: "Russian Federation", code: "RU" },
  { name: "RWANDA", code: "RW" },
  { name: "Saint Helena", code: "SH" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Pierre and Miquelon", code: "PM" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia and Montenegro", code: "CS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Svalbard and Jan Mayen", code: "SJ" },
  { name: "Swaziland", code: "SZ" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syrian Arab Republic", code: "SY" },
  { name: "Taiwan, Province of China", code: "TW" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania, United Republic of", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tokelau", code: "TK" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Turks and Caicos Islands", code: "TC" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "United States Minor Outlying Islands", code: "UM" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Venezuela", code: "VE" },
  { name: "Viet Nam", code: "VN" },
  { name: "Virgin Islands, British", code: "VG" },
  { name: "Virgin Islands, U.S.", code: "VI" },
  { name: "Wallis and Futuna", code: "WF" },
  { name: "Western Sahara", code: "EH" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];

const jobCategories = [
  "Software Development",
  "Web Development",
  "Mobile App Development",
  "UI/UX Design",
  "Graphic Design",
  "Content Writing",
  "Technical Writing",
  "Digital Marketing",
  "SEO & SEM",
  "Email Marketing",
  "Video Editing",
  "Photography",
  "Data Science",
  "Machine Learning & AI",
  "Cybersecurity",
  "Blockchain & Cryptocurrency",
  "Finance & Accounting",
  "Bookkeeping",
  "Legal Consulting",
  "HR & Recruitment",
  "Business Consulting",
  "Virtual Assistance",
  "Sales & Lead Generation",
  "Customer Support",
  "E-commerce & Dropshipping",
  "Game Development",
  "Embedded Systems & IoT",
  "Electrical & Electronics Engineering",
  "CAD & 3D Modeling",
  "Architecture & Interior Design",
  "Healthcare & Medical Writing",
  "E-learning & Training",
  "Podcast Editing & Production",
  "Event Planning",
  "Public Relations",
  "Government & Public Sector",
  "NFT & Web3",
  "Enterprise Solutions",
];

const skills = [
  "JavaScript",
  "TypeScript",
  "Python",
  "C++",
  "C#",
  "Java",
  "React",
  "Next.js",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Ruby on Rails",
  "PHP",
  "Laravel",
  "Vue.js",
  "Angular",
  "WordPress",
  "Shopify",
  "Magento",
  "HTML & CSS",
  "TailwindCSS",
  "Bootstrap",
  "Figma",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adobe After Effects",
  "Final Cut Pro",
  "Blender",
  "Maya",
  "Unreal Engine",
  "Unity",
  "SQL",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "NoSQL",
  "Firebase",
  "Google Ads",
  "Facebook Ads",
  "Amazon FBA",
  "Dropshipping",
  "Python Data Science",
  "R Programming",
  "Big Data",
  "Power BI",
  "Tableau",
  "Copywriting",
  "Ghostwriting",
  "Translation & Localization",
  "Transcription",
  "Data Entry",
  "CRM Management",
  "Customer Service",
  "Salesforce",
  "Trello & Asana",
  "Scrum & Agile",
  "SAP & ERP Systems",
  "HR Management",
  "Legal Writing",
  "Contract Law",
  "Corporate Law",
  "Intellectual Property",
  "Social Media Management",
  "Influencer Marketing",
  "Public Relations",
  "Audio Editing",
  "Music Production",
  "Podcast Production",
  "Blockchain Development",
  "Smart Contracts",
  "Cybersecurity Risk Assessment",
  "Penetration Testing",
  "Cloud Computing",
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "IoT & Embedded Systems",
  "AutoCAD",
  "3D Printing",
  "Motion Graphics",
  "SaaS Development",
  "Game Design",
  "E-learning Development",
];

const industrySkillsMapping = {
  "Software Development": [
    "JavaScript",
    "TypeScript",
    "Python",
    "C++",
    "C#",
    "Java",
    "Node.js",
    "Express.js",
    "Django",
    "Flask",
  ],
  "Web Development": [
    "JavaScript",
    "React",
    "Node.js",
    "HTML & CSS",
    "TailwindCSS",
    "Next.js",
    "Vue.js",
    "Angular",
    "PHP",
    "Laravel",
    "WordPress",
  ],
  "Mobile App Development": [
    "Java",
    "Kotlin",
    "Swift",
    "React Native",
    "Flutter",
    "Firebase",
  ],
  "UI/UX Design": [
    "Figma",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "HTML & CSS",
    "Prototyping",
  ],
  "Graphic Design": [
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Blender",
    "Maya",
    "Motion Graphics",
  ],
  "Content Writing": [
    "Copywriting",
    "Ghostwriting",
    "Translation & Localization",
    "Transcription",
  ],
  "Technical Writing": [
    "Copywriting",
    "Technical Documentation",
    "Markdown",
    "Translation & Localization",
  ],
  "Digital Marketing": [
    "Google Ads",
    "Facebook Ads",
    "Social Media Management",
    "Influencer Marketing",
    "Email Marketing",
  ],
  "SEO & SEM": [
    "Google Ads",
    "Keyword Research",
    "Analytics",
    "Content Optimization",
  ],
  "Email Marketing": [
    "Copywriting",
    "CRM Management",
    "Email Automation",
    "Analytics",
  ],
  "Video Editing": [
    "Adobe After Effects",
    "Final Cut Pro",
    "Motion Graphics",
    "Video Production",
  ],
  Photography: ["Adobe Photoshop", "Lightroom", "Photo Editing", "Composition"],
  "Data Science": [
    "Python Data Science",
    "R Programming",
    "SQL",
    "Big Data",
    "Tableau",
    "Power BI",
  ],
  "Machine Learning & AI": [
    "Python",
    "R Programming",
    "TensorFlow",
    "PyTorch",
    "Big Data",
  ],
  Cybersecurity: [
    "Penetration Testing",
    "Cybersecurity Risk Assessment",
    "Cloud Computing",
    "Network Security",
  ],
  "Blockchain & Cryptocurrency": [
    "Blockchain Development",
    "Smart Contracts",
    "Solidity",
    "Cryptography",
  ],
  "Finance & Accounting": [
    "SAP & ERP Systems",
    "Excel",
    "Bookkeeping",
    "Financial Analysis",
  ],
  Bookkeeping: ["Excel", "QuickBooks", "SAP & ERP Systems", "Data Entry"],
  "Legal Consulting": [
    "Legal Writing",
    "Contract Law",
    "Corporate Law",
    "Intellectual Property",
  ],
  "HR & Recruitment": [
    "HR Management",
    "CRM Management",
    "Trello & Asana",
    "Recruitment Strategies",
  ],
  "Business Consulting": [
    "Scrum & Agile",
    "SAP & ERP Systems",
    "Data Analysis",
    "Strategic Planning",
  ],
  "Virtual Assistance": [
    "Data Entry",
    "CRM Management",
    "Trello & Asana",
    "Customer Service",
  ],
  "Sales & Lead Generation": [
    "Salesforce",
    "CRM Management",
    "Google Ads",
    "Cold Calling",
  ],
  "Customer Support": [
    "Customer Service",
    "CRM Management",
    "Salesforce",
    "Communication Skills",
  ],
  "E-commerce & Dropshipping": [
    "Shopify",
    "Magento",
    "Amazon FBA",
    "Dropshipping",
    "SEO",
  ],
  "Game Development": [
    "Unreal Engine",
    "Unity",
    "C#",
    "Blender",
    "Game Design",
  ],
  "Embedded Systems & IoT": [
    "C++",
    "IoT & Embedded Systems",
    "Python",
    "Hardware Programming",
  ],
  "Electrical & Electronics Engineering": [
    "Embedded Systems",
    "Circuit Design",
    "MATLAB",
    "IoT",
  ],
  "CAD & 3D Modeling": [
    "AutoCAD",
    "Blender",
    "Maya",
    "3D Printing",
    "SolidWorks",
  ],
  "Architecture & Interior Design": [
    "AutoCAD",
    "Blender",
    "3D Modeling",
    "SketchUp",
  ],
  "Healthcare & Medical Writing": [
    "Technical Writing",
    "Medical Terminology",
    "Research",
    "Documentation",
  ],
  "E-learning & Training": [
    "E-learning Development",
    "Instructional Design",
    "Content Creation",
    "LMS Platforms",
  ],
  "Podcast Editing & Production": [
    "Audio Editing",
    "Music Production",
    "Podcast Production",
    "Adobe Audition",
  ],
  "Event Planning": [
    "Project Management",
    "Trello & Asana",
    "Budgeting",
    "Coordination",
  ],
  "Public Relations": [
    "Public Relations",
    "Social Media Management",
    "Copywriting",
    "Media Outreach",
  ],
  "Government & Public Sector": [
    "Policy Analysis",
    "Legal Writing",
    "Data Analysis",
    "Documentation",
  ],
  "NFT & Web3": [
    "Blockchain Development",
    "Smart Contracts",
    "NFT Creation",
    "Web3.js",
  ],
  "Enterprise Solutions": [
    "SAP & ERP Systems",
    "Cloud Computing",
    "AWS",
    "Azure",
    "SaaS Development",
  ],
};

const jobTypes = [
  "Full-time",
  "Part-time",
  "Freelance",
  "Contract-based",
  "Remote",
  "Onsite",
  "Hybrid",
  "Internship",
  "Temporary",
];

const experienceLevels = [
  "Entry Level",
  "Intermediate",
  "Expert",
  "Senior Level",
  "Lead",
];

const projectDurations = [
  "Short-term (Less than 1 month)",
  "Medium-term (1-3 months)",
  "Long-term (3+ months)",
  "Ongoing",
  "One-time Task",
];

const budgetOptions = [
  "Fixed Price",
  "Hourly Rate",
  "Negotiable",
  "Equity-Based",
];

const additionalTags = [
  "Urgent",
  "Flexible Deadline",
  "Startup",
  "Corporate",
  "E-commerce",
  "SaaS",
  "Non-Profit",
  "AI & Automation",
  "Big Data",
  "Enterprise Solutions",
  "Open Source",
  "Government & Public Sector",
  "Funded Project",
  "Equity-Based Compensation",
  "Mentorship Available",
];

module.exports = {
  users,
  countries,
  ongoingProjects,
  jobCategories,
  skills,
  jobTypes,
  experienceLevels,
  projectDurations,
  budgetOptions,
  additionalTags,
  languageTags,
  industrySkillsMapping,
};
