const users = [
  {
    name: "John Doe",
    message: "Pick me at 9:00 AM",
    image: "/images/placeholder-614.webp",
    time: "9:00 AM",
    id: 1,
  },
  {
    name: "Jane Smith",
    message: "Hi Sam, Welcome",
    image: "/images/placeholder-614.webp",
    time: "9:00 AM",
    id: 2,
  },
  {
    name: "Michael Johnson",
    message: "Micheal : Thanks Everyone",
    image: "/images/placeholder-614.webp",
    time: "9:00 AM",
    id: 3,
  },
  {
    name: "Sarah Thompson",
    message: "Sarah : some one can fix this",
    image: "/images/placeholder-614.webp",
    time: "9:00 AM",
    id: 4,
  },
  {
    name: "David Wilson",
    message: "David : some one can fix this",
    image: "/images/placeholder-614.webp",
    time: "9:00 AM",
    id: 5,
  },
  {
    name: "Emily Davis",
    message: "Emily : some one can fix this",
    image: "/images/placeholder-614.webp",
    time: "9:00 AM",
    id: 6,
  },
  {
    name: "Daniel Anderson",
    message: "Daniel : some one can fix this",
    image: "/images/placeholder-614.webp",
    time: "9:00 AM",
    id: 7,
  },

  {
    name: "React Developers",
    message: "New hooks tutorial available",
    image: "/images/placeholder-614.webp",
    time: "10:15 AM",
    id: 8,
  },
  {
    name: "Vue Vixens",
    message: "Join our Vue3 webinar",
    image: "/images/placeholder-614.webp",
    time: "11:00 AM",
    id: 9,
  },
  {
    name: "Angular Architects",
    message: "Monthly meeting rescheduled",
    image: "/images/placeholder-614.webp",
    time: "12:45 PM",
    id: 10,
  },
  {
    name: "Python Programmers",
    message: "Hackathon next weekend",
    image: "/images/placeholder-614.webp",
    time: "1:30 PM",
    id: 11,
  },
  {
    name: "Flutter Friends",
    message: "State management discussion",
    image: "/images/placeholder-614.webp",
    time: "2:15 PM",
    id: 12,
  },
  {
    name: "Node.js Ninjas",
    message: "Express vs Koa - which is better?",
    image: "/images/placeholder-614.webp",
    time: "3:00 PM",
    id: 13,
  },
  {
    name: "Blockchain Buffs",
    message: "Smart contract workshop",
    image: "/images/placeholder-614.webp",
    time: "3:45 PM",
    id: 14,
  },
  {
    name: "AI Enthusiasts",
    message: "New ML model released",
    image: "/images/placeholder-614.webp",
    time: "4:30 PM",
    id: 15,
  },
  {
    name: "Cybersecurity Circle",
    message: "Vulnerability analysis session",
    image: "/images/placeholder-614.webp",
    time: "5:15 PM",
    id: 16,
  },
  {
    name: "DevOps Dudes",
    message: "CI/CD pipeline setup guide",
    image: "/images/placeholder-614.webp",
    time: "6:00 PM",
    id: 17,
  },
];

module.exports = users;
